import { useEffect, useMemo, useState } from "react";
import { Application, extend } from "@pixi/react";
import { AnimatedSprite, Assets, Container, Texture } from "pixi.js";
import {
  AtlasManifestEntry,
  atlasUrl,
  loadAtlasManifest,
} from "@/lib/pixi/manifest";

extend({ Container, AnimatedSprite });

function AtlasStage({ entry }: { entry: AtlasManifestEntry }) {
  const [textures, setTextures] = useState<Texture[] | null>(null);

  useEffect(() => {
    let cancelled = false;
    setTextures(null);
    Assets.load(atlasUrl(entry)).then((sheet: { textures: Record<string, Texture> }) => {
      if (cancelled) return;
      setTextures(Object.values(sheet.textures));
    });
    return () => {
      cancelled = true;
    };
  }, [entry]);

  if (!textures || textures.length === 0) return null;

  return (
    <pixiContainer x={180} y={180}>
      <pixiAnimatedSprite
        textures={textures}
        anchor={{ x: 0.5, y: 0.5 }}
        scale={{ x: 5, y: 5 }}
        loop
        autoPlay
        animationSpeed={entry.mode === "grid" ? 0.18 : 0.06}
      />
    </pixiContainer>
  );
}

export default function SpriteLabPage() {
  const [manifest, setManifest] = useState<AtlasManifestEntry[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [index, setIndex] = useState(0);

  useEffect(() => {
    loadAtlasManifest()
      .then((entries) => {
        // Prefer real animation sheets first -- more interesting to land on.
        const sorted = [...entries].sort((a, b) =>
          a.mode === b.mode ? 0 : a.mode === "grid" ? -1 : 1
        );
        setManifest(sorted);
      })
      .catch((e) => setError(String(e)));
  }, []);

  const grouped = useMemo(() => {
    if (!manifest) return [];
    const byPack = new Map<string, AtlasManifestEntry[]>();
    manifest.forEach((e) => {
      if (!byPack.has(e.pack)) byPack.set(e.pack, []);
      byPack.get(e.pack)!.push(e);
    });
    return [...byPack.entries()];
  }, [manifest]);

  const entry = manifest?.[index];

  return (
    <main className="min-h-screen bg-gradient-to-b from-gray-900 to-black text-white">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <p className="text-xs tracking-widest uppercase text-teal-400 mb-2">
          derelict &middot; asset pipeline
        </p>
        <h1 className="text-2xl font-semibold mb-2">Sprite Lab</h1>
        <p className="text-gray-400 text-sm mb-8 max-w-prose">
          Every atlas generated by <code className="text-teal-300">scripts/build-atlases.mjs</code> from{" "}
          <code className="text-teal-300">asset_zips/</code>, loaded live through Pixi&apos;s{" "}
          <code className="text-teal-300">Assets</code> loader. &ldquo;grid&rdquo; atlases are real
          animation frames sliced by true cell size read from the source{" "}
          <code className="text-teal-300">.aseprite</code> file; &ldquo;flood&rdquo; atlases cycle
          through every distinct sprite the pipeline found on a sheet via connected-component
          detection, so a clean cycle here confirms clean boundaries.
        </p>

        {error && <p className="text-red-400">{error}</p>}
        {!manifest && !error && <p className="text-gray-500">Loading manifest…</p>}

        {manifest && entry && (
          <div className="grid grid-cols-1 sm:grid-cols-[360px_1fr] gap-6 items-start">
            <div className="border border-white/10 rounded bg-black/40 overflow-hidden">
              <Application width={360} height={360} background="#0c0a08">
                <AtlasStage entry={entry} />
              </Application>
            </div>

            <div className="flex flex-col gap-4">
              <div className="flex gap-2">
                <button
                  className="px-3 py-1.5 text-xs uppercase tracking-wide border border-teal-700 text-teal-300 rounded hover:bg-teal-900/40"
                  onClick={() => setIndex((i) => (i - 1 + manifest.length) % manifest.length)}
                >
                  Prev
                </button>
                <button
                  className="px-3 py-1.5 text-xs uppercase tracking-wide border border-teal-700 text-teal-300 rounded hover:bg-teal-900/40"
                  onClick={() => setIndex((i) => (i + 1) % manifest.length)}
                >
                  Next
                </button>
                <span className="text-xs text-gray-500 self-center">
                  {index + 1} / {manifest.length}
                </span>
              </div>

              <select
                className="bg-black/40 border border-white/10 rounded px-2 py-1.5 text-sm"
                value={index}
                onChange={(e) => setIndex(Number(e.target.value))}
              >
                {grouped.map(([pack, entries]) => (
                  <optgroup key={pack} label={pack}>
                    {entries.map((e) => (
                      <option key={e.atlas} value={manifest.indexOf(e)}>
                        {e.name} ({e.frameCount})
                      </option>
                    ))}
                  </optgroup>
                ))}
              </select>

              <dl className="text-sm text-gray-400 grid grid-cols-[auto_1fr] gap-x-3 gap-y-1">
                <dt className="text-gray-600">pack</dt>
                <dd>{entry.pack}</dd>
                <dt className="text-gray-600">sheet</dt>
                <dd className="break-all">{entry.name}</dd>
                <dt className="text-gray-600">mode</dt>
                <dd>{entry.mode === "grid" ? "grid-slice (true frames)" : "flood-fill (detected sprites)"}</dd>
                <dt className="text-gray-600">frames</dt>
                <dd>{entry.frameCount}</dd>
                <dt className="text-gray-600">source</dt>
                <dd className="break-all text-gray-500">{entry.sourcePath}</dd>
              </dl>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
